parameters:
    env(RABBITMQ_DSN): 'amqp://guest:guest@192.168.99.100:5672/%2f'
    my_super_bus.middleware:
        - { id: handle_message }

services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    # Message Bus with it alias
    my_super_bus:
        class: Symfony\Component\Messenger\MessageBus
        tags: [messenger.bus]
        arguments: [[]]

    Symfony\Component\Messenger\MessageBusInterface: '@my_super_bus'

    messenger.middleware.handle_message:
        class: Symfony\Component\Messenger\Middleware\HandleMessageMiddleware
        abstract: true
        arguments: [[], true]

    # Transport Factory - AMQP transport
    Symfony\Component\Messenger\Transport\AmqpExt\AmqpTransportFactory:
        tags: [messenger.transport_factory]
        arguments:
            $debug: '%kernel.debug%'

    # Transport
    messenger.transport.amqp:
        class: Symfony\Component\Messenger\Transport\TransportInterface
        factory: 'Symfony\Component\Messenger\Transport\AmqpExt\AmqpTransportFactory:createTransport'
        arguments:
            $dsn: '%env(RABBITMQ_DSN)%'
            $options: []
